# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import komica_api_pb2 as komica__api__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in komica_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SidecarApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBoards = channel.unary_unary(
                '/news_hub.extension.twkevinzhang.komica.SidecarApi/GetBoards',
                request_serializer=komica__api__pb2.GetBoardsReq.SerializeToString,
                response_deserializer=komica__api__pb2.GetBoardsRes.FromString,
                _registered_method=True)
        self.GetThreads = channel.unary_unary(
                '/news_hub.extension.twkevinzhang.komica.SidecarApi/GetThreads',
                request_serializer=komica__api__pb2.GetThreadsReq.SerializeToString,
                response_deserializer=komica__api__pb2.GetThreadsRes.FromString,
                _registered_method=True)
        self.GetOriginalPost = channel.unary_unary(
                '/news_hub.extension.twkevinzhang.komica.SidecarApi/GetOriginalPost',
                request_serializer=komica__api__pb2.GetOriginalPostReq.SerializeToString,
                response_deserializer=komica__api__pb2.GetOriginalPostRes.FromString,
                _registered_method=True)
        self.GetReplies = channel.unary_unary(
                '/news_hub.extension.twkevinzhang.komica.SidecarApi/GetReplies',
                request_serializer=komica__api__pb2.GetRepliesReq.SerializeToString,
                response_deserializer=komica__api__pb2.GetRepliesRes.FromString,
                _registered_method=True)
        self.GetComments = channel.unary_unary(
                '/news_hub.extension.twkevinzhang.komica.SidecarApi/GetComments',
                request_serializer=komica__api__pb2.GetCommentsReq.SerializeToString,
                response_deserializer=komica__api__pb2.GetCommentsRes.FromString,
                _registered_method=True)


class SidecarApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBoards(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetThreads(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOriginalPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReplies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetComments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SidecarApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBoards': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBoards,
                    request_deserializer=komica__api__pb2.GetBoardsReq.FromString,
                    response_serializer=komica__api__pb2.GetBoardsRes.SerializeToString,
            ),
            'GetThreads': grpc.unary_unary_rpc_method_handler(
                    servicer.GetThreads,
                    request_deserializer=komica__api__pb2.GetThreadsReq.FromString,
                    response_serializer=komica__api__pb2.GetThreadsRes.SerializeToString,
            ),
            'GetOriginalPost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOriginalPost,
                    request_deserializer=komica__api__pb2.GetOriginalPostReq.FromString,
                    response_serializer=komica__api__pb2.GetOriginalPostRes.SerializeToString,
            ),
            'GetReplies': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReplies,
                    request_deserializer=komica__api__pb2.GetRepliesReq.FromString,
                    response_serializer=komica__api__pb2.GetRepliesRes.SerializeToString,
            ),
            'GetComments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetComments,
                    request_deserializer=komica__api__pb2.GetCommentsReq.FromString,
                    response_serializer=komica__api__pb2.GetCommentsRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'news_hub.extension.twkevinzhang.komica.SidecarApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('news_hub.extension.twkevinzhang.komica.SidecarApi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SidecarApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBoards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/news_hub.extension.twkevinzhang.komica.SidecarApi/GetBoards',
            komica__api__pb2.GetBoardsReq.SerializeToString,
            komica__api__pb2.GetBoardsRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetThreads(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/news_hub.extension.twkevinzhang.komica.SidecarApi/GetThreads',
            komica__api__pb2.GetThreadsReq.SerializeToString,
            komica__api__pb2.GetThreadsRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOriginalPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/news_hub.extension.twkevinzhang.komica.SidecarApi/GetOriginalPost',
            komica__api__pb2.GetOriginalPostReq.SerializeToString,
            komica__api__pb2.GetOriginalPostRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReplies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/news_hub.extension.twkevinzhang.komica.SidecarApi/GetReplies',
            komica__api__pb2.GetRepliesReq.SerializeToString,
            komica__api__pb2.GetRepliesRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetComments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/news_hub.extension.twkevinzhang.komica.SidecarApi/GetComments',
            komica__api__pb2.GetCommentsReq.SerializeToString,
            komica__api__pb2.GetCommentsRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
